### ISSUE TITLE
Request canceled while waiting for connection

### ISSUE THREAD

**Issue by wahyd4** [infinityworks/docker-hub-exporter#11]
Hi there, when I was running this docker image, I got around 80% of the request failed. The following are the docker-compose I used and error response
```yaml
version: "3.5"
services:
  dockerhub-exporter:
    tty: true
    restart: unless-stopped
    ports:
      - 9170:9170
    image: infinityworks/docker-hub-exporter
    environment:
      - IMAGES=wahyd4/aria2-ui,wahyd4/aria2-ariang
```
Error message:
```bash
docker_hub_exporter: 2019/05/07 10:01:42 error  Error converting body to byte array: Get https://hub.docker.com/v2/repositories/wahyd4/aria2-ariang: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
I've tried to change my host machine's dns server to `8.8.8.8`, doesn't work either, then I tried to modify the default timeout option in source code from 5 seconds to 1 minute.  The results become much better,  but I still can see the error happened sometimes.
